server:
  port: 8080

spring:
  application:
    name: foods   
  r2dbc:
    url: ${DATABASE_URL}
    #url: r2dbc:pool:postgresql://postgres.axzbiriaypunthimexpq:foods2024%40vg@aws-0-us-east-1.pooler.supabase.com:6543/postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}  
   


    
