server:
  port: 8080

spring:
  application:
    name: foods   
  r2dbc:
    url: r2dbc:pool:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
    username: postgres.axzbiriaypunthimexpq
    password: foods2024@vg
  #security:
    #oauth2:
      #resourceserver:
        #jwt:
          #issuer-uri: http://localhost:8080/realms/PRS

    #url: ${DATABASE_URL}
    #username: ${DATABASE_USERNAME}
    #password: ${DATABASE_PASSWORD}

    