server:
  port: ${PORT:8080}

spring:
  application:
    name: foods   
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    pool:
      initial-size: 3
      max-size: 15
      max-idle-time: 20m
      validation-query: SELECT 1
      acquire-retry: 3
      acquire-retry-delay: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}  
   


    
