pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    environment {
        SONAR_HOST_URL = 'http://localhost:9000'
        SONAR_TOKEN = credentials('sonar-token')
    }
    stages {
        stage('Clonar Repositorio') {
            steps {
                git branch: 'develop', url: 'https://github.com/SebastianPadin/ms_food.git'
            }
        }
        stage('Compilar') {
            steps {
                bat 'mvn clean install -DskipTests'
            }
        }
        stage('Ejecutar Pruebas Unitarias') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Analizar con SonarQube') {
            steps {
                bat 'mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN'
            }
        }
        stage('Generar Artefacto') {
            steps {
                archiveArtifacts artifacts: '**/*.jar', fingerprint: true
            }
        }
    }
}
