pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Clonar Repositorio') {
            steps {
                git branch: 'develop', url: 'https://github.com/SebastianPadin/ms_food.git'
            }
        }
        stage('Compilar') {
            steps {
                bat 'mvn clean install -DskipTests'
            }
        }
        stage('Ejecutar Pruebas Unitarias') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Generar Artefacto') {
            steps {
                archiveArtifacts artifacts: '**/*.jar', fingerprint: true
            }
        }
    }
}
